# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/liyuan/study/c-s_base_on_libevent

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/liyuan/study/c-s_base_on_libevent

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/liyuan/study/c-s_base_on_libevent/CMakeFiles /home/liyuan/study/c-s_base_on_libevent/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/liyuan/study/c-s_base_on_libevent/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CreateJson

# Build rule for target.
CreateJson: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CreateJson
.PHONY : CreateJson

# fast build rule for target.
CreateJson/fast:
	$(MAKE) -f CMakeFiles/CreateJson.dir/build.make CMakeFiles/CreateJson.dir/build
.PHONY : CreateJson/fast

#=============================================================================
# Target rules for targets named ser

# Build rule for target.
ser: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ser
.PHONY : ser

# fast build rule for target.
ser/fast:
	$(MAKE) -f CMakeFiles/ser.dir/build.make CMakeFiles/ser.dir/build
.PHONY : ser/fast

#=============================================================================
# Target rules for targets named cli

# Build rule for target.
cli: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cli
.PHONY : cli

# fast build rule for target.
cli/fast:
	$(MAKE) -f CMakeFiles/cli.dir/build.make CMakeFiles/cli.dir/build
.PHONY : cli/fast

#=============================================================================
# Target rules for targets named CJsonTool

# Build rule for target.
CJsonTool: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CJsonTool
.PHONY : CJsonTool

# fast build rule for target.
CJsonTool/fast:
	$(MAKE) -f CJsonObject/CMakeFiles/CJsonTool.dir/build.make CJsonObject/CMakeFiles/CJsonTool.dir/build
.PHONY : CJsonTool/fast

#=============================================================================
# Target rules for targets named deam

# Build rule for target.
deam: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 deam
.PHONY : deam

# fast build rule for target.
deam/fast:
	$(MAKE) -f deam/CMakeFiles/deam.dir/build.make deam/CMakeFiles/deam.dir/build
.PHONY : deam/fast

#=============================================================================
# Target rules for targets named deam1

# Build rule for target.
deam1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 deam1
.PHONY : deam1

# fast build rule for target.
deam1/fast:
	$(MAKE) -f deam/CMakeFiles/deam1.dir/build.make deam/CMakeFiles/deam1.dir/build
.PHONY : deam1/fast

client.o: client.cc.o

.PHONY : client.o

# target to build an object file
client.cc.o:
	$(MAKE) -f CMakeFiles/cli.dir/build.make CMakeFiles/cli.dir/client.cc.o
.PHONY : client.cc.o

client.i: client.cc.i

.PHONY : client.i

# target to preprocess a source file
client.cc.i:
	$(MAKE) -f CMakeFiles/cli.dir/build.make CMakeFiles/cli.dir/client.cc.i
.PHONY : client.cc.i

client.s: client.cc.s

.PHONY : client.s

# target to generate assembly for a file
client.cc.s:
	$(MAKE) -f CMakeFiles/cli.dir/build.make CMakeFiles/cli.dir/client.cc.s
.PHONY : client.cc.s

make_test_json_file.o: make_test_json_file.cc.o

.PHONY : make_test_json_file.o

# target to build an object file
make_test_json_file.cc.o:
	$(MAKE) -f CMakeFiles/CreateJson.dir/build.make CMakeFiles/CreateJson.dir/make_test_json_file.cc.o
.PHONY : make_test_json_file.cc.o

make_test_json_file.i: make_test_json_file.cc.i

.PHONY : make_test_json_file.i

# target to preprocess a source file
make_test_json_file.cc.i:
	$(MAKE) -f CMakeFiles/CreateJson.dir/build.make CMakeFiles/CreateJson.dir/make_test_json_file.cc.i
.PHONY : make_test_json_file.cc.i

make_test_json_file.s: make_test_json_file.cc.s

.PHONY : make_test_json_file.s

# target to generate assembly for a file
make_test_json_file.cc.s:
	$(MAKE) -f CMakeFiles/CreateJson.dir/build.make CMakeFiles/CreateJson.dir/make_test_json_file.cc.s
.PHONY : make_test_json_file.cc.s

service.o: service.cc.o

.PHONY : service.o

# target to build an object file
service.cc.o:
	$(MAKE) -f CMakeFiles/ser.dir/build.make CMakeFiles/ser.dir/service.cc.o
.PHONY : service.cc.o

service.i: service.cc.i

.PHONY : service.i

# target to preprocess a source file
service.cc.i:
	$(MAKE) -f CMakeFiles/ser.dir/build.make CMakeFiles/ser.dir/service.cc.i
.PHONY : service.cc.i

service.s: service.cc.s

.PHONY : service.s

# target to generate assembly for a file
service.cc.s:
	$(MAKE) -f CMakeFiles/ser.dir/build.make CMakeFiles/ser.dir/service.cc.s
.PHONY : service.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... CreateJson"
	@echo "... ser"
	@echo "... cli"
	@echo "... CJsonTool"
	@echo "... deam"
	@echo "... deam1"
	@echo "... client.o"
	@echo "... client.i"
	@echo "... client.s"
	@echo "... make_test_json_file.o"
	@echo "... make_test_json_file.i"
	@echo "... make_test_json_file.s"
	@echo "... service.o"
	@echo "... service.i"
	@echo "... service.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

